// Scores the trained valuation model inside the Node API.
//
// Unlike cityProfiles.js — which is a hand-maintained mirror of predict.py's
// constants — nothing here is duplicated. This file evaluates the very same
// valuationModel.json that ml-service/train.py writes and predict.py reads, so
// a property's fair value is identical whether it was computed on Vercel or by
// the Python service. There is no second copy to drift.
//
// The model is a ridge regression on log(price_lakhs) with the standardizer
// already folded into the coefficients, which reduces scoring to one dot
// product and an exp() — no sklearn, no 10 MB pickle, no Python at runtime.

let MODEL = null;
let LOAD_ERROR = null;

try {
  // Generated by `python ml-service/train.py`. Absent on a fresh clone until
  // training has been run once, which is why every consumer must handle null.
  const raw = require('./valuationModel.json');
  if (
    raw &&
    typeof raw.intercept === 'number' &&
    Number.isFinite(raw.intercept) &&
    raw.numeric_weights &&
    typeof raw.numeric_weights === 'object' &&
    raw.city_weights &&
    typeof raw.city_weights === 'object'
  ) {
    MODEL = raw;
  } else {
    throw new Error('valuationModel.json failed integrity checks: invalid schema or non-finite weights.');
  }
} catch (err) {
  LOAD_ERROR = err.message;
}

/**
 * Whether a trained valuation model is loaded.
 *
 * Callers must check this rather than assuming a number comes back. When it is
 * false the recommendation engine drops the value component and renormalises
 * its remaining weights, instead of scoring every listing as fairly priced —
 * a neutral 50 would be an opinion the model never expressed.
 */
function isAvailable() {
  return MODEL !== null;
}

/** Diagnostics for the health endpoint: metrics if loaded, reason if not. */
function modelInfo() {
  if (!MODEL) return { available: false, reason: LOAD_ERROR };
  return { available: true, ...MODEL.metrics };
}

const FURNISHED_CODES = { Unfurnished: 0, 'Semi-Furnished': 1, 'Fully-Furnished': 2 };

// Fallbacks for fields a listing may not carry. These match predict.py's
// num_map defaults so a partially-described property is valued the same way in
// both runtimes rather than one of them treating the gap as zero.
const DEFAULTS = {
  bathrooms: 1,
  age_years: 5,
  parking: 1,
  floor: 3,
  furnished_code: 1,
  crime_score: 2.5,
  school_dist_m: 800,
  hospital_dist_m: 1200,
  metro_dist_m: 1500,
};

const num = (value, fallback) => {
  const n = Number(value);
  return Number.isFinite(n) ? n : fallback;
};

/**
 * Model-predicted fair value in lakhs, or null when no model is loaded.
 *
 * Returns null rather than a formula estimate on purpose: cityProfiles'
 * estimatePrice() is the *input* the training data was generated from, so
 * substituting it here would compare each asking price against the same
 * formula that produced it and report every listing as perfectly fair.
 */
function fairValueLakhs(property = {}) {
  if (!MODEL) return null;

  const area = num(property.area_sqft, 0);
  if (area <= 0) return null;

  const furnishedCode = property.furnished_code != null
    ? num(property.furnished_code, DEFAULTS.furnished_code)
    : (FURNISHED_CODES[property.furnished] ?? DEFAULTS.furnished_code);

  const features = {
    // Must match train.py: the model is log-log in area, so the feature is
    // log(area_sqft), not area_sqft. Feeding raw area here would overstate
    // large homes by orders of magnitude.
    log_area: Math.log(area),
    bedrooms: num(property.bedrooms, 2),
    bathrooms: num(property.bathrooms, DEFAULTS.bathrooms),
    age_years: num(property.age_years, DEFAULTS.age_years),
    parking: num(property.parking, DEFAULTS.parking),
    floor: num(property.floor, DEFAULTS.floor),
    furnished_code: furnishedCode,
    crime_score: num(property.crime_score, DEFAULTS.crime_score),
    school_dist_m: num(property.school_dist_m, DEFAULTS.school_dist_m),
    hospital_dist_m: num(property.hospital_dist_m, DEFAULTS.hospital_dist_m),
    metro_dist_m: num(property.metro_dist_m, DEFAULTS.metro_dist_m),
  };

  let logPrice = MODEL.intercept;
  for (const [name, weight] of Object.entries(MODEL.numeric_weights)) {
    logPrice += weight * (features[name] ?? 0);
  }

  // An unlisted city contributes nothing and falls back to the intercept —
  // a blended national baseline. Deliberate: borrowing another city's
  // coefficient would price Kanpur like whichever city sorted first.
  logPrice += MODEL.city_weights[property.city] ?? 0;

  const fair = Math.exp(logPrice);
  if (!Number.isFinite(fair) || fair <= 0) return null;

  return Math.round(fair * 100) / 100;
}

// Half the width of the band that maps onto the 0..1 score. The exported
// median absolute percentage error sits well inside 15%, so a listing beyond
// this is mispriced by more than the model's own noise.
const BAND = 0.15;

/**
 * How well a listing's asking price compares to its modelled fair value.
 *
 * `score` is 0..1 for the recommendation weighting; 0.5 means priced exactly
 * at fair value, above means a discount to it. Returns null when no model is
 * loaded so callers can tell "no opinion" apart from "priced fairly".
 */
function valueAssessment(property = {}) {
  const fair = fairValueLakhs(property);
  const asking = num(property.price_lakhs, 0);
  if (fair == null || asking <= 0) return null;

  const ratio = fair / asking;
  const score = Math.max(0, Math.min(1, (ratio - (1 - BAND)) / (2 * BAND)));

  return {
    score,
    fair_value_lakhs: fair,
    // Positive = asking below modelled value. Surfaced so the UI can say
    // "12% below modelled value" instead of only showing a bare score.
    discount_pct: Math.round((ratio - 1) * 1000) / 10,
  };
}

module.exports = { isAvailable, modelInfo, fairValueLakhs, valueAssessment };
